name: Go Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Ensure go.mod is tidy
      run: go mod tidy && git diff --exit-code go.mod go.sum
      
    - name: Vet Go code
      run: go vet ./...

    - name: Run tests
      run: ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
